alert('Hello,syujiro!);
alert(1+1);
alert(Math.sqrt(1+1));
alert(2の平方根と３の平方根の和を計算しなさい)
alert(1を０で割るとどうなるか。試してみなさい)
alert(0を０で割るとどうなるか、試してみなさい)
alert(2+3)
alert('2'+'3')
alertNumber('2')+Number('3')
alert('2'+3)
alertNumber('2')+3
