alert('Hello,syujiro!);
alert(1+1);
alert(Math.sqrt(1+1));
alert(2の平方根と3の平方根の和)
alert(1を0で割るとどうなるか、試しなさい。)
alert(0を0で割るとどうなるか、試しなさい。)
alert(2+3)
alert('2'+'3')
alert(Number('2')+Number('3')
alert('2'+3)
alert(Number('2')+3)
