alert('Hello,syujiro!);
alert(１+１);
alert(Math.sqrt(１+１));
alert(２の平方根と３の平方根の和を計算しなさい。)
alert(１を０で割るとどうなるか、試しなさい。)
alert(０を０で割るとどうなるか、試しなさい。)
alert(２+３)
alert('２'+'３')
alert(Number('２')+Number('３')
alert('２'+３)
alert(Number('２')+３)
